DROP DATABASE IF EXISTS ygc_Spring;
CREATE DATABASE ygc_Spring;
USE ygc_Spring;

-- Table 추가
CREATE TABLE `member` (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	loginId	CHAR(100) UNIQUE	NOT NULL,
	loginPw	CHAR(200)	NOT NULL,
	`name` CHAR(100)	NOT NULL,
	nickname	CHAR(100)	NOT NULL,
	regDate	DATETIME	NOT NULL,
	updateDate	DATETIME	NOT NULL,
	cellPhoneNum	CHAR(20)	NOT NULL,
	email	CHAR(50)	NOT NULL,
	profileImage	VARCHAR(255)	NULL,
	favoritePlayerId	INT(10) UNSIGNED NULL,
	messageToPlayer	TEXT	NULL,
	authLevel	SMALLINT(2) UNSIGNED	NOT NULL	DEFAULT 3	COMMENT '권한 (관리자 = 7, 일반유저 = 3)',
	delStatus	TINYINT(1) UNSIGNED	NOT NULL	DEFAULT 0	COMMENT '탈퇴 여부 (탈퇴 전 =  0, 탈퇴 후 = 1)',
	delDate	DATETIME	NULL	COMMENT '탈퇴 날짜'
);

CREATE TABLE player (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	`name`	CHAR(100) NOT NULL,
	teamName	CHAR(100) NOT NULL,
	height	INT(5)	NOT NULL,
	weight	INT(5)	NOT NULL,
	`number`	INTEGER(5)	NULL,
	`position`	CHAR(10)	NOT NULL,
	birthDate	CHAR(20)	NOT NULL,
	profileImage	VARCHAR(255)	NULL	COMMENT 'NULL 허용 사진 없는 경우도 있기 때문에',
	career	VARCHAR(255)	NOT NULL
);

CREATE TABLE memberProfileImage (
	id INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY, 
	memberId INT(10) UNSIGNED	NOT NULL,
	imagePath VARCHAR(255)	NOT NULL,
	regDate	DATETIME	NULL,
	updateDate	DATETIME	NULL
);

CREATE TABLE playerProfileImage (
	id INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	playerId INT(10) UNSIGNED NOT NULL,
	imagePath VARCHAR(255) NOT NULL,
	regDate	DATETIME NULL,
	updateDate DATETIME	NULL
);

CREATE TABLE team (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	`name`	CHAR(20)	NOT NULL
);

CREATE TABLE stadiumImage (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	stadiumId	INT(10) UNSIGNED	NOT NULL,
	imagePath	VARCHAR(255)	NOT NULL,
	regDate	DATETIME	NULL,
	updateDate	DATETIME	NULL
);

CREATE TABLE stadium (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	teamId	INT(10) UNSIGNED	NOT NULL,
	`name`	CHAR(20)	NOT NULL,
	address CHAR(100)	NOT NULL,
	image	VARCHAR(255)	NULL
);

CREATE TABLE logoType (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	teamId	INT(10) UNSIGNED NOT NULL,
	image	VARCHAR(255)	NULL
);

CREATE TABLE logoTypeImage (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	logoTypeId	INT(10) UNSIGNED	NOT NULL,
	imagePath	VARCHAR(255)	NOT NULL,
	regDate	DATETIME	NULL,
	updateDate	DATETIME	NULL
);

CREATE TABLE game (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	gameStadiumName	CHAR(20)	NOT NULL,
	gameStartDate	DATETIME	NOT NULL,
	gameResult	CHAR(50)	NOT NULL,
	homeTeamScore	INT	NOT NULL	DEFAULT 0,
	awayTeamScore	INT	NOT NULL	DEFAULT 0,
	homeTeamId INT(10) UNSIGNED	NOT NULL,
	awayTeamId INT(10) UNSIGNED	NOT NULL
);

CREATE TABLE atBat (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	gameId	INT(10) UNSIGNED	NOT NULL,
	inning	INT	NOT NULL,
	result	DATETIME	NOT NULL	COMMENT '삼진, 땅볼, 플라이아웃, 안타, 홈런, 실책, 다른사유 등',
	rbi	INT	NOT NULL	DEFAULT 0,
	run	INT	NOT NULL	DEFAULT 0,
	batterId INT(10) UNSIGNED	NOT NULL,
	pitcherId INT(10) UNSIGNED	NOT NULL
);

CREATE TABLE article (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	memberId INT(10) UNSIGNED	NOT NULL,
	boardId	INT(10) UNSIGNED	NOT NULL,
	title	CHAR(100)	NOT NULL,
	`body`	TEXT	NOT NULL,
	regDate	DATETIME	NOT NULL,
	updateDate	DATETIME	NOT NULL,
	hitCount	INT(10) UNSIGNED	NOT NULL	DEFAULT 0,
	goodReactionPoint	INT(10) UNSIGNED	NOT NULL	DEFAULT 0,
	badReactionPoint	INT(10) UNSIGNED	NOT NULL	DEFAULT 0
);

CREATE TABLE reply (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	memberId	INT(10) UNSIGNED	NOT NULL,
	relTypeCode	CHAR(50)	NOT NULL,
	relId	INT(10)	NOT NULL,
	`body`	TEXT	NOT NULL,
	regDate	DATETIME	NOT NULL,
	updateDate	DATETIME	NOT NULL,
	goodReactionPoint	INT(10) UNSIGNED	NOT NULL	DEFAULT 0,
	badReactionPoint	INT(10) UNSIGNED	NULL	DEFAULT 0
);

CREATE TABLE reactionPoint (
    id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	memberId	INT(10) UNSIGNED	NOT NULL,
	relTypeCode	CHAR(50)	NOT NULL,
	relId	INT(10)	NOT NULL,
	`body`	TEXT	NOT NULL,
	regDate	DATETIME	NOT NULL,
	updateDate	DATETIME	NOT NULL,
	`point`	INT(10)	NOT NULL
);

CREATE TABLE board (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	regDate	DATETIME	NOT NULL,
	updateDate	DATETIME	NOT NULL,
	`code`	CHAR(50) UNIQUE	NOT NULL	COMMENT 'notice(공지사항) free(자유)...',
	`name`	CHAR(20) UNIQUE	NOT NULL	COMMENT '게시판 이름',
	delStatus	TINYINT(1) UNSIGNED	NULL	COMMENT '삭제 여부 (0=삭제 전, 1=삭제 후)',
	delDate	DATETIME	NULL	COMMENT '삭제 날짜'
);

CREATE TABLE BatterSeasonStats (
	id	INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	playerId	INT(10) UNSIGNED NOT NULL,
	teamName	VARCHAR(50)	NOT NULL,
	seasonYear	INT(10) UNSIGNED,
	gamesPlayed	INT(10) UNSIGNED,
	pa	INT(10) UNSIGNED,
	atBat	INT(10) UNSIGNED,
	run	INT(10) UNSIGNED,
	hit	INT(10) UNSIGNED,
	`double` INT(10) UNSIGNED,
	triple	INT(10) UNSIGNED,
	homeRun	INT(10) UNSIGNED,
	rbi	INT(10) UNSIGNED,
	stolenBase	INT(10) UNSIGNED,
	caughtStealing	INT(10) UNSIGNED,
	walk	INT(10) UNSIGNED,
	strikeout	INT(10) UNSIGNED,
	hitByPitch	INT(10) UNSIGNED,
	sacrificeFly INT(10) UNSIGNED,
	battingAverage	FLOAT UNSIGNED,
	onBasePercentage	FLOAT UNSIGNED,
	sluggingPercentage	FLOAT UNSIGNED,
	ops	FLOAT UNSIGNED	NOT NULL,
	doublePlay	INT(10) UNSIGNED,
	`error`	INT(10) UNSIGNED
);

CREATE TABLE PitcherSeasonStats (
	id	INT UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY, 
	playerId	INT(10) UNSIGNED	NOT NULL,
	teamName	VARCHAR(50)	NOT NULL,
	seasonYear	INT(10),
    win	INT(10) UNSIGNED,
	lose INT(10) UNSIGNED,
	era	FLOAT UNSIGNED,
	gamesPlayed	INT(10),
	completeGame INT(10) UNSIGNED,
	shutout	INT(10) UNSIGNED,
	save	INT(10) UNSIGNED,
	hold	INT(10) UNSIGNED,
	inning	FLOAT UNSIGNED,
	hitAllowed	INT(10) UNSIGNED,
	doubleAllowed	INT(10) UNSIGNED,
	tripleAllowed	INT(10) UNSIGNED,
	homeRunAllowed	INT(10) UNSIGNED,
	runAllowed	INT(10) UNSIGNED,
	earnedRun	INT(10) UNSIGNED,
	walk	INT(10) UNSIGNED,
	strikeout	INT(10) UNSIGNED,
	whip	FLOAT UNSIGNED,
	hitByPitch	INT(10) UNSIGNED,
	balk	INT(10) UNSIGNED,
	wildPitch	INT(10) UNSIGNED,
	battersFaced INT(10) UNSIGNED
);

CREATE TABLE TeamSeasonStats (
	id	INT(10) UNSIGNED AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	teamId	INT(10) UNSIGNED	NOT NULL,
	teamName	VARCHAR(50)	NOT NULL,
	seasonYear	INT(10) UNSIGNED,
	win	INT(10) UNSIGNED,
	lose	INT(10) UNSIGNED,
	draw	INT(10) UNSIGNED,
	runsScored	INT(10) UNSIGNED,
	runsAllowed	INT(10) UNSIGNED,
	homeRun	INT(10) UNSIGNED,
	stolenBase	INT(10) UNSIGNED,
	`error`	INT(10) UNSIGNED
);

-- 여기까지 Table 추가


-- FOREIGN KEY 추가
ALTER TABLE memberProfileImage ADD CONSTRAINT FK_memberProfileImage_member FOREIGN KEY (memberId) REFERENCES `member`(id)
ON DELETE CASCADE;

ALTER TABLE playerProfileImage ADD CONSTRAINT FK_playerProfileImage_player FOREIGN KEY (playerId) REFERENCES player(id)
ON DELETE CASCADE;

ALTER TABLE stadiumImage ADD CONSTRAINT FK_stadiumImage_stadium FOREIGN KEY (stadiumId) REFERENCES stadium(id)
ON DELETE CASCADE;

ALTER TABLE stadium ADD CONSTRAINT FK_stadium_team FOREIGN KEY (teamId) REFERENCES team(id)
ON DELETE CASCADE;

ALTER TABLE logoType ADD CONSTRAINT FK_logoType_team FOREIGN KEY (teamId) REFERENCES team(id)
ON DELETE CASCADE;

ALTER TABLE logoTypeImage ADD CONSTRAINT FK_logoTypeImage_logoType FOREIGN KEY (logoTypeId) REFERENCES logoType(id)
ON DELETE CASCADE;

ALTER TABLE game ADD CONSTRAINT FK_game_homeTeam FOREIGN KEY (homeTeamId) REFERENCES team(id)
ON DELETE CASCADE;

ALTER TABLE game ADD CONSTRAINT FK_game_awayTeam FOREIGN KEY (awayTeamId) REFERENCES team(id)
ON DELETE CASCADE;

ALTER TABLE atBat ADD CONSTRAINT FK_atBat_game FOREIGN KEY (gameId) REFERENCES game(id)
ON DELETE CASCADE;

ALTER TABLE atBat ADD CONSTRAINT FK_atBat_batter FOREIGN KEY (batterId) REFERENCES player(id)
ON DELETE CASCADE;

ALTER TABLE atBat ADD CONSTRAINT FK_atBat_pitcher FOREIGN KEY (pitcherId) REFERENCES player(id)
ON DELETE CASCADE;

ALTER TABLE article ADD CONSTRAINT FK_article_member FOREIGN KEY (memberId) REFERENCES `member`(id)
ON DELETE CASCADE;

ALTER TABLE reply ADD CONSTRAINT FK_reply_member FOREIGN KEY (memberId) REFERENCES `member`(id)
ON DELETE CASCADE;

ALTER TABLE reactionPoint ADD CONSTRAINT FK_reactionPoint_member FOREIGN KEY (memberId) REFERENCES `member`(id)
ON DELETE CASCADE;

ALTER TABLE BatterSeasonStats ADD CONSTRAINT FK_BatterSeasonStats_player FOREIGN KEY (playerId) REFERENCES player(id)
ON DELETE CASCADE;

ALTER TABLE PitcherSeasonStats ADD CONSTRAINT FK_PitcherSeasonStats_player FOREIGN KEY (playerId) REFERENCES player(id)
ON DELETE CASCADE;

ALTER TABLE TeamSeasonStats ADD CONSTRAINT FK_TeamSeasonStats_team FOREIGN KEY (teamId) REFERENCES team(id)
ON DELETE CASCADE;
-- 여기까지 외래키 추가

SELECT * FROM `member`;
SELECT * FROM player;
